spring:
  application:
    name: image-service

#  datasource:
#    url: jdbc:mysql://192.168.80.128:3306/emall
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  config:
      import: "optional:configserver:http://localhost:8089"


