server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:s:
    health:
      show-details: ALWAYS

spring:
  application:
    name: eureka-service