spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8089"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

  data:
    redis:
      host: 192.168.80.128
      port: 6379
      connect-timeout: 1000
      timeout: 5000

resilience4j:
  circuitbreaker:
    #instances:
     # foroneofservice: name of the circuit breaker for oneofservice
       # registerCircuitBreakerMBean: true
      #  registerHealthIndicator: true
       # slidingWindowSize: 5
       # minimumNumberOfCalls: 5
       # failureRateThreshold: 50
       # waitDurationInOpenState: 10s
       # permittedNumberOfCallsInHalfOpenState: 3
       # eventConsumerBufferSize: 10
    configs:
        default:
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 100
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 60s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10

# application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有 Actuator 端点
  endpoint:
    health:
      show-details: always


